### ISSUE TITLE
Implement safe_cast macro

### ISSUE THREAD

**Issue by adamtwo** [Teradata/dbt-teradata-utils#1]
### Describe the feature
Currently,`dbt-teradata-utils` doesn't implement `safe_cast` macro. As a result, `dbt-utils` defaults to the standard `cast(var as type)` syntax. Teradata supports `trycast` which doesn't error out when the cast cannot be done. `dbt-teradata-utils` should  have an implementation of `safe_cast` that uses `trycast`.

### Describe alternatives you've considered
Continue with the current non-safe implementation.

### Additional context
See https://github.com/dbt-labs/dbt-utils/blob/main/macros/cross_db_utils/safe_cast.sql

### Who will this benefit?
`safe_cast` is useful when we can't be certain about data types and formats.

**Comment by VarunSharma15** [comment]
Safe_cast macro was implemented in dbt-terdata 1.8.2
https://github.com/Teradata/dbt-teradata/pull/198
Closing the issue
