### ISSUE TITLE
date_spine is mentioned in the documentation but is not provided.

### ISSUE THREAD

**Issue by Daniel-Itzul** [Teradata/dbt-teradata-utils#4]
### Describe the bug
Reference date_spine macro in a model

### Steps To Reproduce
There was an error at execution because date_spine is not included in the macros available though it is mentioned as a custom provided macro in the documentation. What is offered is a datediff.

### Expected behavior
Either the custom macro is provided or it is not mentioned as a custom provided macro in the documentation.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

**The output of `dbt --version`:**
```
1.3.3
```

**The operating system you're using:**

Windows

**The output of `python --version`:**

3.10

**Comment by adamtwo** [comment]
Daniel,
When this plugin was released, `data_spine` macro was provided by `dbt-utils`. The only thing that `dbt-teradata-utils` had to do to be compatible with `dbt-utils` was to override `generate_series`. The macro worked even though it was not implemented in the plugin.

Now the situation got a little bit complex. In version 1.3 dbt moved the cross-db macros to dbt-core. To match that, we also moved our cross-db macros from `dbt-teradata-utils` to `dbt-teradata`. We didn't move `generate_series`. 

Have you tried installing the extension and using `data_spine` with the extension installed?

**Comment by Daniel-Itzul** [comment]
Hi Adam,

If by the extension you mean dbt_utils, yes both dbt_utils and teradata_utils are installed and the dispatch is set to look first at teradata_utils for the dbt_utils macro namespace.

The macro date_spine does exist in the dbt_utils package, though, as mentioned it doesn't exist in teradata_utils. 

In light of your comment, I venture to think that we are facing the following:

* I see that date_spine in dbt utils does mentions both generate_series and datediff, both of which do exist still as part of teradata_utils. 
* generate_series in dbt_utils still is called under the namespace dbt_utils, so I guess that one is not the issue.
* datediff, on the other hand, is directly under the dbt namespace, I think that is the culprit since being under that namespace it doesn't point to the teradata version. 
* In line of the above I think either we will have to move our datediff to core, or still provide the custom macro.

**Comment by VarunSharma15** [comment]
Hi @Daniel-Itzul , 
This issue has been resolved with the latest dbt-teradata-utils 1.1.1 and dbt-teradata 1.6.7
Although, with 1.7.x dbt has moved the date_spine() to core , which we are working on right now.
But for now, date_spine() is working and generate_series() has also been overridden in dbt-teradata-utils latest release.
