### ISSUE TITLE
introspective macro get_column_values fails due to incorrect number of parameters though it is copy verbatim from dbt_documentation

### ISSUE THREAD

**Issue by Daniel-Itzul** [Teradata/dbt-teradata-utils#5]
### Describe the bug
Introspective macro get_column_values fails due to incorrect number of parameters though it is copy verbatim from dbt_documentation.

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

macro is called in this block, following the exact way it is implemented in dbt_utils documentation.
{% set product_categories = dbt_utils.get_column_values(table=ref('product_order_totals'), column='category') %}

result when the model that has this code is implemented.

Compilation Error in model order_categories (models\marts\intermediate\order_categories.sql)
  macro 'dbt_macro__default__get_column_values' takes not more than 5 argument(s)

Dispatch is set in the dbt_project configuration as to look first in teradata_utils regarding the dbt_utils macro name space.

### Expected behavior

This should work.
### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

**The output of `dbt --version`:**
```
1.3.3
```

**The operating system you're using:**
Windows

**The output of `python --version`:**
3.10

**Comment by VarunSharma15** [comment]
Hi @Daniel-Itzul ,
This issue has been fixed with the latest version dbt-teradata-utils 1.1.1 and dbt-teradata 1.6.7
